version: '3'
services:
  app:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - contenta
    volumes:
      - www:/var/www
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - www:/var/www
    env_file:
      - .env
    networks:
      - contenta
  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    networks: 
      - contenta

volumes:
  data:
  www:

networks:
  contenta: 
